### ISSUE TITLE
record_two_mics.sh file of beyond1lte

### ISSUE THREAD

**Issue by 1eethink** [PowerPhone/PowerPhone#1]
Hi, I've followed your friendly instructions.
To test whether I correctly follow them, I record simple 25000 Hz sound and it seems not working.
Also, I failed to execute the bash file.
The commands said that tinymix and tinycap are inaccessible or not found.

"""
127|beyond1lte:/ # sh /data/tmp/record_two_mics.sh
/data/tmp/record_two_mics.sh[4]: tinymix: inaccessible or not found
/data/tmp/record_two_mics.sh[5]: tinymix: inaccessible or not found
/data/tmp/record_two_mics.sh[6]: tinymix: inaccessible or not found
/data/tmp/record_two_mics.sh[7]: tinymix: inaccessible or not found
/data/tmp/record_two_mics.sh[8]: tinymix: inaccessible or not found
/data/tmp/record_two_mics.sh[9]: tinymix: inaccessible or not found
/data/tmp/record_two_mics.sh[10]: tinymix: inaccessible or not found
/data/tmp/record_two_mics.sh[11]: tinymix: inaccessible or not found
/data/tmp/record_two_mics.sh[12]: tinymix: inaccessible or not found
/data/tmp/record_two_mics.sh[13]: tinymix: inaccessible or not found
/data/tmp/record_two_mics.sh[14]: tinymix: inaccessible or not found
/data/tmp/record_two_mics.sh[15]: tinymix: inaccessible or not found
/data/tmp/record_two_mics.sh[16]: tinymix: inaccessible or not found
/data/tmp/record_two_mics.sh[19]: tinymix: inaccessible or not found
/data/tmp/record_two_mics.sh[21]: tinymix: inaccessible or not found
/data/tmp/record_two_mics.sh[23]: tinymix: inaccessible or not found
/data/tmp/record_two_mics.sh[24]: tinymix: inaccessible or not found
/data/tmp/record_two_mics.sh[25]: tinymix: inaccessible or not found
/data/tmp/record_two_mics.sh[26]: tinymix: inaccessible or not found
/data/tmp/record_two_mics.sh[27]: tinymix: inaccessible or not found
/data/tmp/record_two_mics.sh[28]: tinymix: inaccessible or not found
/data/tmp/record_two_mics.sh[30]: tinycap: inaccessible or not found
"""

How can I fix this problem?
And are there any differences between recording with commands and Recorder App.?
Also, are there any useful tools to analyze the ultrasound like Figure 7 in your paper?
Lastly, how can I make the chirp signals in smartphone?
(I'm new to this field, so I'm sorry for asking those questions.)

Plus, I recently found that the recorded sound of m4a file remains below 4 kHz.
Did I do something wrong?
![1 m4a](https://github.com/PowerPhone/PowerPhone/assets/106564466/9071c4d0-a820-49f6-9a5d-f3eba460d7e2)

Thank you.

**Comment by charlescao460** [comment]
Hi Hojeong, thank you very much for trying our project. I'm willing to help you to reproduce the 192kHz recording in the Samsung Galaxy S10. 

1. Could you please confirm that you have flashed the smartphone with LineageOS? If so, it seems that they removed the tinyALSA utilities from their release. And that's probably the reason you couldn't access `tinycap`, `tinyplay`, and `tinymix`. To fix the problem, could you please try [this images](https://github.com/PowerPhone/PowerPhone/releases/download/release/lineage_beyond1lte-ota-eng.ubuntu.zip)?
2. The `tinycap` and `tinyplay` can interact directly with the HAL without passing through Android Framework, which may down-sample or cause glitches in the audio. So, we recommend using tinyALSA (`tinycap` and `tinyplay`) for the best acoustic performance. Other than that, any Android App will utilize Android API to do the recording and playing which will go through the Framework and System Services layers. 
3. To measure the frequency response, the easiest way is through [REW](https://www.roomeqwizard.com/), although it was not purposed for acoustic sensing. A frequency response can be done easily with a simple FFT in the MATLAB, if you don't observe any non-linear distortion. If you do have non-linearities, you will need to filter out the unwanted frequency components before doing the FFT. We also recommend using [Adobe Audition](https://www.adobe.com/products/audition.html) to quickly inspect the audio signals, as its visualization is very useful. 
5. Chirp signals can be generated through any programming language easily. Let's take MATLAB as an example, the chirp signals is can be generated by [chirp() function](https://www.mathworks.com/help/signal/ref/chirp.html) and then you should use [audiowrite() function](https://www.mathworks.com/help/matlab/ref/audiowrite.html) to write to .wav files. In practices, we generate multiples chirps in one file and play the whole file.  Please note that when using `tinyplay`, the sampling rates and channels must match the hardware settings. If you experience pop-click noise, you should applying windowing to do the fade-in and fade-out. 
6. You should observer higher frequency components once you fix the recording through tinycap.

**Comment by 1eethink** [comment]
Hi, thanks for replying.
The tools you mentioned above will help me a lot.

I've tried with your images in the comment above with heimdall, but when I clicked "Reboot system now" the first boot never ends.
![image](https://github.com/PowerPhone/PowerPhone/assets/106564466/2fc6089c-0ff0-49c6-9013-f30342fce3c1)
But it booted successfully with the image on the [github link.](https://download.lineageos.org/devices/beyond1lte/builds)

I found tinyalsa github page.
https://github.com/tinyalsa/tinyalsa
So I plan to try to flash with the latest image below (same as on your github page), then build tinyalsa using "Soong".
https://download.lineageos.org/devices/beyond1lte/builds
Do you think this will work properly?

Thank you.

**Comment by charlescao460** [comment]
Hi, 

If the first boot loops you can try reboot. Otherwise it might because you installed Android 13 (LineageOS 20) and having problem downgrading to LineageOS 19. 

Cross-compiling tinyALSA would definitely works. All you need is [NDK](https://developer.android.com/ndk/downloads), compiling  tinyALSA you found on GitHub using the clang you found in the NDK. Copy the compiled `tinycap`, `tinyplay` and `tinymix` and add them to PATH to the smartphone would work.

**Comment by 1eethink** [comment]
Hi,

I finally cross-compiled and now the commands `tinycap`, `tinyplay` and `tinymix` work.
I also changed "tinymix" to "tinymix set" in record_two_mics.sh file because it works instead of "tinymix".
However, when I execute the file, it shows errors like below.
![image](https://github.com/PowerPhone/PowerPhone/assets/106564466/1e2a389d-2a53-472b-90f3-ae93c53c8d16)

To figure out what's going on, I found that below four commands cause the errors.
tinymix set "Sample Rate 2" "192kHz"
tinymix set "ASYNC Sample Rate 2" "192kHz"
tinymix set "IN3 OSR" "6.144MHz"
tinymix set "IN4 OSR" "6.144MHz"

How can I fix this problem?
Did I miss something?
I've done in Samsung Galaxy S10 with [Lineage OS](https://download.lineageos.org/devices/beyond1lte/builds).
I hope that I'm almost ready for the ultrasound recording. :)

Thank you.

**Comment by charlescao460** [comment]
Interesting, could you please still try using our images? By follow these steps:
1. Flash an official Android 12 ROM 
2. Flash our recovery: https://github.com/PowerPhone/PowerPhone/releases/download/release/recovery-beyond1lte.img
3. Boot into recovery, flash our system: https://github.com/PowerPhone/PowerPhone/releases/download/release/lineage_beyond1lte-ota-eng.ubuntu.zip

It seems that the official LineageOS images has changed a lot for the past year. And if it still doesn't work, we can schedule a call. 

Thanks!

**Comment by 1eethink** [comment]
I tried in two Galaxy S10 phones (KT and SKT), but it still does not work.
(same as my comment above that the first boot never ends)
I'll email you to make an appointment.

**Comment by charlescao460** [comment]
Hi, I've replied to your emails about the time slot. 

Could you please tell me the exact smartphone model number of your S10 (E.g. SM-G973F)?

**Comment by 1eethink** [comment]
Hi,
both phones I've tried are SM-G973N.

-----Original Message-----
